name: Build 9008 APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # 1. 准备环境 (已修正适配 Ubuntu 24.04)
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade buildozer cython virtualenv
          
      # 2. 拉取 EDL 源码 (修正版)
      - name: Clone EDL Source
        run: |
          # 只有当 edl 文件夹不存在时才执行
          if [ ! -d "edl" ]; then
            echo "正在下载 EDL 源码..."
            # 1. 下载到临时文件夹 'temp_repo'，避免名字冲突
            git clone https://github.com/bkerler/edl.git temp_repo
            
            # 2. 把里面的核心 'edl' 文件夹移出来
            mv temp_repo/edl .
            
            # 3. 删除临时文件夹
            rm -rf temp_repo
            echo "EDL 源码准备完毕！"
          fi

      # 3. 开始编译
      - name: Build APK
        run: |
          yes | buildozer android debug

      # 4. 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 9008_Tool_APK
          path: bin/*.apk
